# Generated by Django 5.0.1 on 2024-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
